### ISSUE TITLE
python prepross_data.py, Exception: (standalone) cannot create context

### ISSUE THREAD

**Issue by Aoihigashi** [tangjiapeng/DiffuScene#15]
(diffuscene5) root@rtx6:/workspace/caitou/DiffuScene1/scripts# python preprocess_data.py /workspace/caitou/DiffuScene1/3d_front_processed/livingrooms_objfeats_32_64 /workspace/caitou/DiffuScene1/3D-FRONT/3D-FRONT /workspace/caitou/DiffuScene1/3D-FUTURE-model/3D-FUTURE-model /workspace/caitou/DiffuScene1/3D-FUTURE-model/3D-FUTURE-model/model_info.json --dataset_filtering threed_front_livingroom --annotation_file /workspace/caitou/DiffuScene1/config/livingroom_threed_front_splits.csv --add_objfeats
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
Traceback (most recent call last):
  File "preprocess_data.py", line 355, in <module>
    main(sys.argv[1:])
  File "preprocess_data.py", line 147, in main
    scene = scene_from_args(args)
  File "/workspace/caitou/DiffuScene1/scripts/utils.py", line 244, in scene_from_args
    scene = Scene(size=args.window_size, background=args.background)
  File "/workspace/conda/envs/diffuscene5/lib/python3.8/site-packages/simple_3dviz/scenes.py", line 112, in __init__
    super(Scene, self).__init__(size, background, ctx)
  File "/workspace/conda/envs/diffuscene5/lib/python3.8/site-packages/simple_3dviz/scenes.py", line 23, in __init__
    self._ctx = moderngl.create_standalone_context()
  File "/workspace/conda/envs/diffuscene5/lib/python3.8/site-packages/moderngl/__init__.py", line 1960, in create_standalone_context
    return create_context(standalone=True, **kwargs)
  File "/workspace/conda/envs/diffuscene5/lib/python3.8/site-packages/moderngl/__init__.py", line 1931, in create_context
    ctx.mglo, ctx.version_code = mgl.create_context(glversion=require, mode=mode, **settings)
  File "/workspace/conda/envs/diffuscene5/lib/python3.8/site-packages/glcontext/__init__.py", line 90, in create
    return x11.create_context(**kwargs)
Exception: (standalone) cannot create context

**Comment by Aoihigashi** [comment]
I wonder why I can't create context, is this something wrong with x11 forwarding? how can I solve this problem, thank you.

**Comment by tangjiapeng** [comment]
Hi, it seems the problem is caused by the opengl library dependencies.
 "libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)"
