### ISSUE TITLE
XOpenDisplay: cannot open display

### ISSUE THREAD

**Issue by qiuzidian** [tangjiapeng/DiffuScene#40]
Hi, when I run preprocess_data. py on a remote server, the error message is as follows. Does this mean I need a graphical interface?

Traceback (most recent call last):
  File "preprocess_data.py", line 355, in <module>
    main(sys.argv[1:])
  File "preprocess_data.py", line 147, in main
    scene = scene_from_args(args)
  File "/home/zitian/work/DiffuScene/scripts/utils.py", line 244, in scene_from_args
    scene = Scene(size=args.window_size, background=args.background)
  File "/home/zitian/anaconda3/envs/diffuscene/lib/python3.8/site-packages/simple_3dviz/scenes.py", line 110, in __init__
    super(Scene, self).__init__(size, background, ctx)
  File "/home/zitian/anaconda3/envs/diffuscene/lib/python3.8/site-packages/simple_3dviz/scenes.py", line 22, in __init__
    self._ctx = moderngl.create_standalone_context()
  File "/home/zitian/anaconda3/envs/diffuscene/lib/python3.8/site-packages/moderngl/__init__.py", line 2014, in create_standalone_context
    return create_context(standalone=True, **kwargs)
  File "/home/zitian/anaconda3/envs/diffuscene/lib/python3.8/site-packages/moderngl/__init__.py", line 1964, in create_context
    ctx.mglo, ctx.version_code = mgl.create_context(glversion=require, mode=mode, **settings)
  File "/home/zitian/anaconda3/envs/diffuscene/lib/python3.8/site-packages/glcontext/__init__.py", line 90, in create
    return x11.create_context(**kwargs)
Exception: (standalone) XOpenDisplay: cannot open display

**Comment by silvester666** [comment]
hi, I have the same error when I run generate_diffusion.py. Do you have a solution to this error?

**Comment by luzhiyuan25** [comment]
I also have the same error when I run generate_diffusion.py. Do you have a solution to this error?
