### ISSUE TITLE
There are two errors in process_data program

### ISSUE THREAD

**Issue by VV940** [tangjiapeng/DiffuScene#47]
The texture class in the program defines Ns, but there is no Ns data in the mtl file.

Another issue is that the ambient data written is inconsistent with the defined one.
Traceback (most recent call last):
  File "preprocess_data.py", line 355, in <module>
    main(sys.argv[1:])
  File "preprocess_data.py", line 344, in main
    render(
  File "/home/hps/py_project/DiffuScene-master/scripts/utils.py", line 234, in render
    scene.add(r)
  File "/home/hps/anaconda3/envs/diffuscene/lib/python3.8/site-packages/simple_3dviz/scenes.py", line 60, in add
    renderable.init(self._ctx)
  File "/home/hps/anaconda3/envs/diffuscene/lib/python3.8/site-packages/simple_3dviz/renderables/textured_mesh.py", line 197, in init
    self.material = self._material
  File "/home/hps/anaconda3/envs/diffuscene/lib/python3.8/site-packages/simple_3dviz/renderables/textured_mesh.py", line 229, in material
    self._prog["ambient"].write(self._material.ambient.tobytes())
  File "/home/hps/anaconda3/envs/diffuscene/lib/python3.8/site-packages/_moderngl.py", line 95, in write
    self.ctx._write_uniform(
_moderngl.Error: invalid uniform size

Look forward to your answer, thank you

**Comment by tangjiapeng** [comment]
I uploaded the preprocessed dataset, and you can directly use mine without re-processing.

Please check my update!
